# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7df3935e62780474985fd47eab0437731e9e397c3f71668abd60b4294cf1ff35d4b9f2e46eb1979d1266b625938f306b5aab9c22154572e6d99d628d4c1ef0e

test:
  secret_key_base: f134087999992c20518e829cb7b0a390b555fc3772c11cd722151636ae7204a118f5b6b08aae44af1231e7ebf8cbeaa3f8a3eb3890955fca45382e41318e5729

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
